spring: 
  application: 
    name: getarea
  datasource:
    getarea: 
      mysql: #mysql 数据库连接信息
        url: jdbc:mysql://127.0.0.1:3306/area_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        validation-query: select 1
        test-on-borrow: true
        test-while-idle: true
        test-on-connect: true
        min-idle: 40
        max-idle: 50
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss Z
    time-zone: GMT+8      
    
# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server: # 内置tomcat配置
  port: 5679 # 服务端口，默认为8080
  context-path: /getarea 
  session-timeout: 60 # session最大超时时间(分钟)，默认为30
  tomcat: 
    max-threads: 800 # tomcat最大线程数，默认为200
    uri-encoding: UTF-8 # tomcat的URI编码
    


